name: Standard Build Check

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      vss-version:
        required: false
        type: string
  workflow_call:
    inputs:
      vss-version:
        required: false
        type: string


env:
  PYTHON_VERSION: "3.10.6" # keep in sync with vss-tools

jobs:
  buildtest:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -V
          python -m pip --quiet --no-input install --upgrade pip
          python -m pip --quiet --no-input install --upgrade wheel
          python -m pip --quiet --no-input install --upgrade pytest
          python -m pip --quiet --no-input install --upgrade git+https://github.com/COVESA/vss-tools@master
          echo done!

      - name: Build Targets
        run: |
          if [ "${{ inputs.vss-version }}" != "" ]; then
            export VSS_VERSION="${{ inputs.vss-version }}"
          fi
          make VERBOSE=1

      - name: "Uploading artifacts"
        uses: actions/upload-artifact@v7
        with:
          name: acea-vss-artifacts
          path: |
            generated/
          if-no-files-found: error

      - name: Run Tests
        run: |
          make test
